### ISSUE TITLE
Apply Patch Error

### ISSUE THREAD

**Issue by shuaixSu** [zhangyang-intel/turtlebot3_modified#1]
Hi, when i fllow 2.1  and run git apply 0001-fix-the-problem-that-the-odometry-may-publish-an-out.patch 
feed back Error: error:unrecognized input 
**my step:**
$cd /turtlebot3_ws/src
$git clone -b foxy-devel https://github.com/ROBOTIS-GIT/DynamixelSDK.git
$git clone -b foxy-devel https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
$git clone -b foxy-devel https://github.com/ROBOTIS-GIT/turtlebot3.git
$cd ./turtlebot3
$git apply 0001-fix-the-problem-that-the-odometry-may-publish-an-out.patch
#i have not this file(0001-fix-the-problem-that-the-odometry-may-publish-an-out.patch),so i excute
$wget https://github.com/zhangyang-intel/turtlebot3_modified/blob/foxy-devel/collaborative_slam_fullstack_doc/0001-fix-the-problem-that-the-odometry-may-publish-an-out.patch
$git apply 0001-fix-the-problem-that-the-odometry-may-publish-an-out.patch
#error: unrecognized input 
so Is there a problem with my steps, or can you tell me how to fix this ,thanks

**Comment by zhangyang-intel** [comment]
hi，i am sorry to see your issue just now.
Its seems that the patch files produced by "git diff" and "git format-patch" are different.
I update the patch file and test it.

**Comment by zhangyang-intel** [comment]
hi，i am sorry to see your issue just now.
Its seems that the patch files produced by "git diff" and "git format-patch" are different.
I update the patch file and test it.

**Comment by shuaixSu** [comment]
Hi ,please update patch link in chapter 2.1, i will dowland it and test it or i can get it other way

**Comment by zhangyang-intel** [comment]
Hi, run "wget https://github.com/zhangyang-intel/turtlebot3_modified/blob/foxy-devel/collaborative_slam_fullstack_doc/remove_outlier.patch"

**Comment by shuaixSu** [comment]
hi , thanks ,i dowload remove_outlier.patch file and excute $git apply remove_outlier.patch ,but not work ,#error: unrecognized input still print ,then i fllow this file edit corresponding content
